import { Article } from "./types";

export const mockArticles: Article[] = [
  {
    id: "1",
    source: "KHIDI",
    date: "2026.01.19",
    title: "2026년 바이오헬스 산업 육성 전략 발표 - R&D 투자 3조원 확대",
    summary: "한국보건산업진흥원이 2026년 바이오헬스 산업 육성 전략을 발표했다. 바이오의약품, 디지털헬스케어, 의료기기 분야에 총 3조원 규모의 R&D 투자가 이루어질 예정이며, 글로벌 시장 진출을 위한 인허가 지원도 강화된다.",
    link: "https://www.khidi.or.kr/board?menuId=MENU00085",
    isNew: true,
    tags: {
      type: "브리핑",
      category: "R&D정책",
      layer: "보건산업브리프",
      region: "국내",
      source: "KHIDI",
    },
  },
  {
    id: "2",
    source: "KHIDI",
    date: "2026.01.18",
    title: "디지털치료제(DTx) 산업 동향 및 2026년 전망",
    summary: "글로벌 디지털치료제 시장이 2026년 100억 달러를 돌파할 전망이다. 국내에서도 정신건강, 당뇨관리 분야 DTx 개발이 활발하며, 건강보험 급여 적용 논의가 본격화되고 있다.",
    link: "https://www.khidi.or.kr/board?menuId=MENU00949",
    isNew: true,
    tags: {
      type: "브리핑",
      category: "디지털헬스케어",
      layer: "글로벌동향",
      region: "글로벌",
      source: "KHIDI",
    },
  },
  {
    id: "3",
    source: "식약처",
    date: "2026.01.17",
    title: "AI 의료기기 허가 가이드라인 개정안 행정예고",
    summary: "식품의약품안전처가 AI 기반 의료기기의 허가·심사 가이드라인 개정안을 행정예고했다. 소프트웨어 의료기기(SaMD)의 임상 평가 기준과 사후관리 체계가 강화된다.",
    link: "https://www.mfds.go.kr",
    isNew: true,
    tags: {
      type: "뉴스",
      category: "규제인허가",
      layer: "정책보고서",
      region: "국내",
      source: "식약처",
    },
  },
  {
    id: "4",
    source: "KHIDI",
    date: "2026.01.16",
    title: "2026년 상반기 KHIDI 정규직 채용 공고",
    summary: "한국보건산업진흥원이 2026년 상반기 정규직 신입/경력 채용을 실시한다. 모집 분야는 디지털헬스 사업관리, 바이오의약품 PM, 글로벌 사업지원 등 총 15명 내외이며, 원서접수는 2월 1일부터 시작된다.",
    link: "https://www.khidi.or.kr/recruit",
    isNew: false,
    tags: {
      type: "채용공고",
      category: "채용분석",
      layer: "뉴스레터",
      region: "국내",
      source: "KHIDI",
    },
  },
  {
    id: "5",
    source: "KHIDI",
    date: "2026.01.15",
    title: "[인바스켓 예시] 바이오시밀러 수출 확대 전략 수립",
    summary: "상황: 국내 바이오시밀러 기업의 유럽 시장 진출이 지연되고 있음. 과제: EMA 인허가 대응 전략 및 현지 파트너십 구축 방안을 수립하시오. KHIDI R&D사업본부 주임 관점에서 답안을 작성해보세요.",
    link: "#",
    isNew: false,
    tags: {
      type: "인바스켓",
      category: "글로벌진출",
      layer: "연구보고서",
      region: "유럽",
      source: "KHIDI",
    },
  },
  {
    id: "6",
    source: "복지부",
    date: "2026.01.14",
    title: "보건의료 빅데이터 플랫폼 고도화 사업 추진",
    summary: "보건복지부가 보건의료 빅데이터 플랫폼 고도화 사업을 본격 추진한다. 의료데이터 연계 확대, AI 분석 기능 강화, 데이터 품질 관리 체계 구축이 핵심 과제이다.",
    link: "https://www.mohw.go.kr",
    isNew: false,
    tags: {
      type: "뉴스",
      category: "헬스케어IT",
      layer: "정책보고서",
      region: "국내",
      source: "복지부",
    },
  },
  {
    id: "7",
    source: "KHIDI",
    date: "2026.01.13",
    title: "미국 FDA 의료기기 인허가 동향 - 510(k) 심사 현대화",
    summary: "FDA가 510(k) 심사 현대화 프로그램을 확대 시행한다. AI/ML 기반 의료기기, 사이버보안 요구사항, Real-World Evidence 활용 관련 주요 변경사항을 분석한다.",
    link: "https://www.khidi.or.kr/board?menuId=MENU00949",
    isNew: false,
    tags: {
      type: "브리핑",
      category: "규제인허가",
      layer: "글로벌동향",
      region: "북미",
      source: "KHIDI",
    },
  },
  {
    id: "8",
    source: "산업부",
    date: "2026.01.12",
    title: "의료기기 산업 수출 200억불 달성 기념 성과보고회",
    summary: "산업통상자원부가 의료기기 산업 수출 200억 달러 달성을 기념하는 성과보고회를 개최했다. 진단기기, AI 의료기기, 수술로봇 분야가 수출 성장을 견인했다.",
    link: "https://www.motie.go.kr",
    isNew: false,
    tags: {
      type: "뉴스",
      category: "의료기기",
      layer: "뉴스레터",
      region: "글로벌",
      source: "산업부",
    },
  },
  {
    id: "9",
    source: "KHIDI",
    date: "2026.01.11",
    title: "세포·유전자치료제 시장 동향 및 국내 기업 현황",
    summary: "글로벌 세포·유전자치료제 시장이 연평균 30% 이상 성장하고 있다. 국내에서도 CAR-T, 유전자편집 치료제 개발이 활발하며, 임상 3상 진입 기업이 증가하고 있다.",
    link: "https://www.khidi.or.kr/board?menuId=MENU00085",
    isNew: false,
    tags: {
      type: "브리핑",
      category: "제약바이오",
      layer: "보건산업브리프",
      region: "글로벌",
      source: "KHIDI",
    },
  },
  {
    id: "10",
    source: "KHIDI",
    date: "2026.01.10",
    title: "보건산업 인력 수급 전망 2026 - 디지털헬스 전문가 부족",
    summary: "2026년 보건산업 인력 수급 전망 보고서가 발표되었다. 디지털헬스케어, 바이오데이터 사이언스, RA(규제과학) 분야의 전문 인력 부족이 심화될 것으로 예상된다.",
    link: "https://www.khidi.or.kr/board?menuId=MENU00094",
    isNew: false,
    tags: {
      type: "브리핑",
      category: "인력양성",
      layer: "백서",
      region: "국내",
      source: "KHIDI",
    },
  },
  {
    id: "11",
    source: "언론보도",
    date: "2026.01.09",
    title: "삼성바이오로직스, 美 빅파마와 5조원 규모 CMO 계약 체결",
    summary: "삼성바이오로직스가 미국 대형 제약사와 5조원 규모의 바이오의약품 위탁생산(CMO) 계약을 체결했다. 이번 계약으로 국내 바이오 CDMO 산업의 글로벌 경쟁력이 입증되었다.",
    link: "https://news.example.com",
    isNew: false,
    tags: {
      type: "뉴스",
      category: "바이오헬스",
      layer: "뉴스레터",
      region: "북미",
      source: "언론보도",
    },
  },
  {
    id: "12",
    source: "KHIDI",
    date: "2026.01.08",
    title: "[인바스켓 예시] 의료기기 규제 샌드박스 사업 기획",
    summary: "상황: 혁신 의료기기 스타트업의 시장 진입이 지연되고 있음. 과제: 규제 샌드박스 제도를 활용한 신속 인허가 지원 사업을 기획하시오. 사업 목표, 대상, 지원 내용, 기대 효과를 포함하세요.",
    link: "#",
    isNew: false,
    tags: {
      type: "인바스켓",
      category: "규제인허가",
      layer: "연구보고서",
      region: "국내",
      source: "KHIDI",
    },
  },
  {
    id: "13",
    source: "KHIDI",
    date: "2026.01.07",
    title: "동남아시아 의료기기 시장 진출 가이드",
    summary: "동남아시아 의료기기 시장 규모가 2026년 150억 달러를 돌파할 전망이다. 베트남, 인도네시아, 태국 등 주요국의 인허가 제도와 시장 진출 전략을 분석한다.",
    link: "https://www.khidi.or.kr/board?menuId=MENU00949",
    isNew: false,
    tags: {
      type: "브리핑",
      category: "글로벌진출",
      layer: "글로벌동향",
      region: "동남아",
      source: "KHIDI",
    },
  },
  {
    id: "14",
    source: "식약처",
    date: "2026.01.06",
    title: "첨단바이오의약품 안전관리 종합계획 발표",
    summary: "식품의약품안전처가 첨단바이오의약품 안전관리 종합계획을 발표했다. 세포치료제, 유전자치료제의 품질관리 기준 강화와 추적관리 시스템 구축이 핵심 내용이다.",
    link: "https://www.mfds.go.kr",
    isNew: false,
    tags: {
      type: "뉴스",
      category: "제약바이오",
      layer: "정책보고서",
      region: "국내",
      source: "식약처",
    },
  },
  {
    id: "15",
    source: "KHIDI",
    date: "2026.01.05",
    title: "감염병 대응 체계 고도화 - K-방역 2.0 전략",
    summary: "보건산업진흥원이 감염병 대응 체계 고도화 전략을 발표했다. 백신·치료제 자급률 향상, 진단키트 개발 지원, 국제 공조 체계 강화가 주요 과제이다.",
    link: "https://www.khidi.or.kr/board?menuId=MENU00085",
    isNew: false,
    tags: {
      type: "브리핑",
      category: "공중보건",
      layer: "보건산업브리프",
      region: "국내",
      source: "KHIDI",
    },
  },
];

export const getLastUpdated = (): string => {
  const now = new Date();
  return now.toLocaleString("ko-KR", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
};
